mage-hand-press-book-of-extinction:
  - "Book of Extinction"
mage-hand-press-dark-matter:
  - "Dark Matter"
mage-hand-press-valdas-spire-of-secrets:
  - "Valda's Spire of Secrets"

mage-hand-press-the-last-owlbear:
  - "The Last Owlbear"
mage-hand-press-strange-owlchemy:
  - "Strange Owlchemy"
