blank_issues_enabled: false
contact_links:
  - name: Purchase Problems
    url: https://magehandpress.com/support/
    about: Problems purchasing content should be handled on the Mage Hand Press website.
